### ISSUE TITLE
列表重用有问题~~库还不错，顶

### ISSUE THREAD

**Issue by Ryan0520** [Akateason/XTFMDB#1]
如题

**Comment by Akateason** [comment]
hi, 能把问题描述的清楚一点吗...在哪里. 哪个地方. 什么问题...

**Comment by Ryan0520** [comment]
@Akateason 只是UI上显示问题，并不是库的问题。
![197ecd0c-1391-46b7-9cf9-e71ff5df0a9c](https://cloud.githubusercontent.com/assets/11271005/25731353/1c1490ca-3178-11e7-8306-88b76c5ab494.png)

**Comment by Akateason** [comment]
哦.我图快.没在意调整界面. 换个分辨率大的模拟器试试

**Comment by Akateason** [comment]
修复了
