### ISSUE TITLE
单引号插入不成功问题？

### ISSUE THREAD

**Issue by shywoody** [Akateason/XTFMDB#7]
数据内容中有有夹杂单引号的就会导致插入不成功, 有什么好的解决方案么

**Comment by shywoody** [comment]
NSString *select=[NSString stringWithFormat:@"INSERT INTO TaskList (keeptime,task) VALUES ('%@','%@')",keepTime,task]; 观察到insert逻辑是类似于这样的，当keeptime或者task字符串内容中带有单引号会导致插入数据失败, 有时特殊的语种中也会包含单引号

**Comment by Akateason** [comment]
首先需要你传入的是一个合法的sql字符串.  
你可以借助sqlite工具看下是哪个特殊字符导致的.  做下特殊字符转义.

**Comment by shywoody** [comment]
> 

好的,谢谢回复🙏
是国际化配置的字典转成了字符串存到了数据库中其中特殊语言的问候语夹杂了单引号,想再请问您有没有什么好的办法建议
目前想到的好像除了手动进行replace  `  to  \\` 操作

**Comment by Akateason** [comment]
你的业务model to -> DBmodel, 有特殊字符的情况在里面处理下. 这个和你手动差不多.

也可以改XT的源码, 提个mr就好了

**Comment by shywoody** [comment]
> 你的业务model to -> DBmodel, 有特殊字符的情况在里面处理下. 这个和你手动差不多.
> 
> 也可以改XT的源码, 提个mr就好了

谢谢耐心解答。peace～
